// SPDX-License-Identifier: MIT
pragma solidity 0.8.35;

import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import {EIP712} from "@openzeppelin/contracts/utils/cryptography/EIP712.sol";
import {SignatureChecker} from "@openzeppelin/contracts/utils/cryptography/SignatureChecker.sol";
import {ReentrancyGuard} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import {Ownable2Step} from "@openzeppelin/contracts/access/Ownable2Step.sol";
import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";

/// @notice Interface for a Groth16 ZK-SNARK verifier contract.
/// Matches the verifyProof signature generated by snarkjs zkey export solidityverifier.
interface IGroth16Verifier {
    /// @param _pA G1 point (curve A)
    /// @param _pB G2 point (curve B) — nested array for pairing-friendly curve
    /// @param _pC G1 point (curve C)
    /// @param _pubSignals Public inputs to the circuit
    function verifyProof(uint[2] calldata _pA, uint[2][2] calldata _pB, uint[2] calldata _pC, uint[2] calldata _pubSignals) external view returns (bool);
}

/// @title AgentWorkEscrowZK
/// @notice ZK-SNARK enhanced USDC escrow for agent-to-agent work on Base/Base Sepolia.
/// @dev v0.6 adds optional on-chain ZK proof verification before fund release.
/// @custom:version 0.6-zk
contract AgentWorkEscrowZK is EIP712, ReentrancyGuard, Ownable2Step {
    using SafeERC20 for IERC20;

    enum Status {
        None,
        Funded,
        ProofSubmitted,
        Released,
        Refunded,
        Disputed,
        Resolved
    }

    struct Intent {
        address buyer;
        address seller;
        uint96 feeBps;
        uint256 amount;
        uint256 createdAt;
        uint256 workDeadline;
        uint256 reviewDeadline;
        uint256 reviewPeriod;
        bytes32 workHash;
        string workURI;
        Status status;
        string proofURI;
        string disputeURI;
    }

    /// @notice ZK-SNARK proof data for an intent
    struct ZKProof {
        uint256[2] pA;       // G1 point
        uint256[2][2] pB;    // G2 point
        uint256[2] pC;       // G1 point
        uint256[2] pubSignals; // Public inputs: [isValid, commitment]
        bool submitted;
    }

    IERC20 public immutable usdc;
    address public feeRecipient;
    IGroth16Verifier public zkVerifier;

    uint96 public defaultFeeBps = 100;
    uint96 public constant MAX_FEE_BPS = 1_000;
    uint96 public constant BPS_DENOMINATOR = 10_000;

    uint256 public constant MIN_WORK_TIMEOUT = 1 hours;
    uint256 public constant MAX_WORK_TIMEOUT = 30 days;
    uint256 public constant MIN_REVIEW_PERIOD = 1 hours;
    uint256 public constant MAX_REVIEW_PERIOD = 14 days;
    uint256 public constant MAX_URI_BYTES = 512;

    bytes32 public constant SELLER_OFFER_TYPEHASH = keccak256(
        "SellerOffer(address buyer,address seller,uint256 amount,bytes32 workHash,bytes32 workURIHash,uint256 workTimeoutSeconds,uint256 reviewPeriodSeconds,uint256 nonce,uint256 offerExpiresAt)"
    );

    uint256 public nextIntentId = 1;
    uint256 public accumulatedFees;

    mapping(uint256 => Intent) public intents;
    mapping(bytes32 => bool) public usedOfferDigests;
    mapping(address => mapping(uint256 => bool)) public cancelledNonces;
    /// @notice ZK proofs submitted per intent
    mapping(uint256 => ZKProof) public zkProofs;

    event IntentCreated(
        uint256 indexed intentId,
        address indexed buyer,
        address indexed seller,
        uint256 amount,
        bytes32 workHash,
        string workURI,
        uint256 workDeadline,
        uint256 reviewPeriod,
        uint96 feeBps
    );
    event SignedOfferFunded(uint256 indexed intentId, bytes32 indexed offerDigest, uint256 nonce);
    event OfferNonceCancelled(address indexed seller, uint256 indexed nonce);
    event ProofSubmitted(uint256 indexed intentId, string proofURI, uint256 reviewDeadline);
    event ZKProofSubmitted(uint256 indexed intentId, uint256 commitment);
    event ZKVerificationFailed(uint256 indexed intentId);
    event ZKVerificationPassed(uint256 indexed intentId);
    event Released(uint256 indexed intentId, uint256 sellerAmount, uint256 feeAmount);
    event ClaimedAfterReview(uint256 indexed intentId, uint256 sellerAmount, uint256 feeAmount);
    event Refunded(uint256 indexed intentId, uint256 amount);
    event Disputed(uint256 indexed intentId, address indexed openedBy, string disputeURI);
    event DisputeResolved(uint256 indexed intentId, uint256 buyerAmount, uint256 sellerAmount, uint256 feeAmount, bool chargeFee);
    event FeesWithdrawn(address indexed recipient, uint256 amount);
    event FeeRecipientUpdated(address indexed feeRecipient);
    event DefaultFeeBpsUpdated(uint96 feeBps);
    event ZKVerifierSet(address indexed verifier);

    error ZeroAddress();
    error InvalidAmount();
    error InvalidTimeout();
    error InvalidReviewPeriod();
    error InvalidFee();
    error InvalidSplit();
    error InvalidURI();
    error UriTooLong();
    error InvalidWorkHash();
    error SelfEscrow();
    error NotBuyer();
    error NotSeller();
    error NotParty();
    error NotFeeRecipient();
    error InvalidStatus();
    error WorkDeadlinePassed();
    error RefundUnavailable();
    error ClaimUnavailable();
    error NoFees();
    error OfferExpired();
    error OfferUsed();
    error OfferCancelled();
    error InvalidSignature();
    error CannotRescueUSDC();
    error ZKProofRequired();
    error ZKProofInvalid();
    error ZKNotConfigured();

    constructor(address usdc_, address feeRecipient_, address initialOwner, address zkVerifier_) EIP712("AI Work Market", "0.6-zk") Ownable(initialOwner) {
        if (usdc_ == address(0) || feeRecipient_ == address(0) || initialOwner == address(0)) revert ZeroAddress();
        usdc = IERC20(usdc_);
        feeRecipient = feeRecipient_;
        if (zkVerifier_ != address(0)) {
            zkVerifier = IGroth16Verifier(zkVerifier_);
        }
    }

    // ============================================================
    // ADMIN
    // ============================================================

    /// @notice Set or update the ZK-SNARK verifier contract.
    /// @param verifier Address of the Groth16 verifier contract. Pass address(0) to disable ZK.
    function setZKVerifier(address verifier) external onlyOwner {
        // Prevent accidentally setting same verifier twice
        if (address(zkVerifier) == verifier) revert InvalidURI();
        zkVerifier = IGroth16Verifier(verifier);
        emit ZKVerifierSet(verifier);
    }

    // ============================================================
    // INTENT CREATION (unchanged from v0.5)
    // ============================================================

    function createIntent(
        address seller,
        uint256 amount,
        uint256 workTimeoutSeconds,
        uint256 reviewPeriodSeconds,
        bytes32 workHash,
        string calldata workURI
    ) external nonReentrant returns (uint256 intentId) {
        intentId = _createIntent(msg.sender, seller, amount, workTimeoutSeconds, reviewPeriodSeconds, workHash, workURI);
    }

    function createIntentFromSignedOffer(
        address seller,
        uint256 amount,
        uint256 workTimeoutSeconds,
        uint256 reviewPeriodSeconds,
        bytes32 workHash,
        string calldata workURI,
        uint256 nonce,
        uint256 offerExpiresAt,
        bytes calldata signature
    ) external nonReentrant returns (uint256 intentId) {
        if (block.timestamp > offerExpiresAt) revert OfferExpired();
        if (cancelledNonces[seller][nonce]) revert OfferCancelled();

        bytes32 offerDigest = getOfferDigest(
            msg.sender,
            seller,
            amount,
            workHash,
            keccak256(bytes(workURI)),
            workTimeoutSeconds,
            reviewPeriodSeconds,
            nonce,
            offerExpiresAt
        );
        if (usedOfferDigests[offerDigest]) revert OfferUsed();
        if (!SignatureChecker.isValidSignatureNow(seller, offerDigest, signature)) revert InvalidSignature();

        usedOfferDigests[offerDigest] = true;
        intentId = _createIntent(msg.sender, seller, amount, workTimeoutSeconds, reviewPeriodSeconds, workHash, workURI);

        emit SignedOfferFunded(intentId, offerDigest, nonce);
    }

    function cancelOfferNonce(uint256 nonce) external {
        cancelledNonces[msg.sender][nonce] = true;
        emit OfferNonceCancelled(msg.sender, nonce);
    }

    function getOfferDigest(
        address buyer,
        address seller,
        uint256 amount,
        bytes32 workHash,
        bytes32 workURIHash,
        uint256 workTimeoutSeconds,
        uint256 reviewPeriodSeconds,
        uint256 nonce,
        uint256 offerExpiresAt
    ) public view returns (bytes32) {
        bytes32 structHash = keccak256(
            abi.encode(
                SELLER_OFFER_TYPEHASH,
                buyer,
                seller,
                amount,
                workHash,
                workURIHash,
                workTimeoutSeconds,
                reviewPeriodSeconds,
                nonce,
                offerExpiresAt
            )
        );
        return _hashTypedDataV4(structHash);
    }

    // ============================================================
    // PROOF SUBMISSION (v0.5 proofURI + new ZK proof)
    // ============================================================

    /// @notice Original v0.5 proof submission via IPFS URI.
    function submitProof(uint256 intentId, string calldata proofURI) external {
        _validateIPFSURI(proofURI);
        Intent storage intent = intents[intentId];
        if (msg.sender != intent.seller) revert NotSeller();
        if (intent.status != Status.Funded) revert InvalidStatus();
        if (block.timestamp >= intent.workDeadline) revert WorkDeadlinePassed();

        uint256 reviewDeadline = block.timestamp + intent.reviewPeriod;
        intent.proofURI = proofURI;
        intent.reviewDeadline = reviewDeadline;
        intent.status = Status.ProofSubmitted;

        emit ProofSubmitted(intentId, proofURI, reviewDeadline);
    }

    /// @notice ZK-enhanced proof submission. Seller submits both an IPFS URI AND a ZK-SNARK proof.
    /// @param intentId The escrow intent ID
    /// @param proofURI IPFS URI linking to off-chain work evidence
    /// @param pA G1 proof point A
    /// @param pB G2 proof point B
    /// @param pC G1 proof point C
    /// @param pubSignals Public signals: [isValid, commitment]
    function submitProofWithZK(
        uint256 intentId,
        string calldata proofURI,
        uint256[2] calldata pA,
        uint256[2][2] calldata pB,
        uint256[2] calldata pC,
        uint256[2] calldata pubSignals
    ) external {
        _validateIPFSURI(proofURI);
        Intent storage intent = intents[intentId];
        if (msg.sender != intent.seller) revert NotSeller();
        if (intent.status != Status.Funded) revert InvalidStatus();
        if (block.timestamp >= intent.workDeadline) revert WorkDeadlinePassed();
        if (address(zkVerifier) == address(0)) revert ZKNotConfigured();

        uint256 reviewDeadline = block.timestamp + intent.reviewPeriod;
        intent.proofURI = proofURI;
        intent.reviewDeadline = reviewDeadline;
        intent.status = Status.ProofSubmitted;

        zkProofs[intentId] = ZKProof({
            pA: pA,
            pB: pB,
            pC: pC,
            pubSignals: pubSignals,
            submitted: true
        });

        emit ProofSubmitted(intentId, proofURI, reviewDeadline);
        emit ZKProofSubmitted(intentId, pubSignals[1]); // commitment
    }

    // ============================================================
    // RELEASE / CLAIM (ZK-verified)
    // ============================================================

    function release(uint256 intentId) external nonReentrant {
        Intent storage intent = intents[intentId];
        if (msg.sender != intent.buyer) revert NotBuyer();
        if (intent.status != Status.ProofSubmitted) revert InvalidStatus();

        // If ZK verifier is configured and a ZK proof exists, verify it
        if (address(zkVerifier) != address(0) && zkProofs[intentId].submitted) {
            ZKProof memory zk = zkProofs[intentId];

            // Verify the ZK proof on-chain
            bool valid = zkVerifier.verifyProof(zk.pA, zk.pB, zk.pC, zk.pubSignals);
            if (!valid) {
                emit ZKVerificationFailed(intentId);
                revert ZKProofInvalid();
            }
            emit ZKVerificationPassed(intentId);
        }

        intent.status = Status.Released;
        (uint256 feeAmount, uint256 sellerAmount) = _feeSplit(intent.amount, intent.feeBps);
        accumulatedFees += feeAmount;
        usdc.safeTransfer(intent.seller, sellerAmount);

        emit Released(intentId, sellerAmount, feeAmount);
    }

    function claimAfterReview(uint256 intentId) external nonReentrant {
        Intent storage intent = intents[intentId];
        if (msg.sender != intent.seller) revert NotSeller();
        if (intent.status != Status.ProofSubmitted) revert InvalidStatus();
        if (block.timestamp < intent.reviewDeadline) revert ClaimUnavailable();

        // If ZK verifier is configured and a ZK proof exists, verify it
        if (address(zkVerifier) != address(0) && zkProofs[intentId].submitted) {
            ZKProof memory zk = zkProofs[intentId];

            bool valid = zkVerifier.verifyProof(zk.pA, zk.pB, zk.pC, zk.pubSignals);
            if (!valid) {
                emit ZKVerificationFailed(intentId);
                revert ZKProofInvalid();
            }
            emit ZKVerificationPassed(intentId);
        }

        intent.status = Status.Released;
        (uint256 feeAmount, uint256 sellerAmount) = _feeSplit(intent.amount, intent.feeBps);
        accumulatedFees += feeAmount;
        usdc.safeTransfer(intent.seller, sellerAmount);

        emit ClaimedAfterReview(intentId, sellerAmount, feeAmount);
    }

    // ============================================================
    // REFUND / DISPUTE / RESOLVE (unchanged)
    // ============================================================

    function refund(uint256 intentId) external nonReentrant {
        Intent storage intent = intents[intentId];
        if (msg.sender != intent.buyer) revert NotBuyer();
        if (intent.status != Status.Funded) revert InvalidStatus();
        if (block.timestamp <= intent.workDeadline) revert RefundUnavailable();

        intent.status = Status.Refunded;
        usdc.safeTransfer(intent.buyer, intent.amount);

        emit Refunded(intentId, intent.amount);
    }

    function dispute(uint256 intentId, string calldata disputeURI) external {
        _validateIPFSURI(disputeURI);
        Intent storage intent = intents[intentId];
        if (msg.sender != intent.buyer && msg.sender != intent.seller) revert NotParty();
        if (intent.status != Status.Funded && intent.status != Status.ProofSubmitted) revert InvalidStatus();

        intent.disputeURI = disputeURI;
        intent.status = Status.Disputed;

        emit Disputed(intentId, msg.sender, disputeURI);
    }

    function resolveDispute(uint256 intentId, uint256 buyerAmount, uint256 sellerAmount, bool chargeFee)
        external
        onlyOwner
        nonReentrant
    {
        Intent storage intent = intents[intentId];
        if (intent.status != Status.Disputed) revert InvalidStatus();
        if (buyerAmount + sellerAmount != intent.amount) revert InvalidSplit();

        intent.status = Status.Resolved;

        uint256 feeAmount = 0;
        uint256 sellerNet = sellerAmount;
        if (chargeFee && sellerAmount > 0) {
            (feeAmount, sellerNet) = _feeSplit(sellerAmount, intent.feeBps);
            accumulatedFees += feeAmount;
        }

        if (buyerAmount > 0) usdc.safeTransfer(intent.buyer, buyerAmount);
        if (sellerNet > 0) usdc.safeTransfer(intent.seller, sellerNet);

        emit DisputeResolved(intentId, buyerAmount, sellerNet, feeAmount, chargeFee);
    }

    function withdrawFees() external nonReentrant {
        if (msg.sender != feeRecipient) revert NotFeeRecipient();
        uint256 amount = accumulatedFees;
        if (amount == 0) revert NoFees();
        accumulatedFees = 0;
        usdc.safeTransfer(feeRecipient, amount);
        emit FeesWithdrawn(feeRecipient, amount);
    }

    function rescueTokens(address token, uint256 amount) external onlyOwner nonReentrant {
        if (token == address(usdc)) revert CannotRescueUSDC();
        IERC20(token).safeTransfer(owner(), amount);
    }

    function setFeeRecipient(address feeRecipient_) external onlyOwner {
        if (feeRecipient_ == address(0)) revert ZeroAddress();
        feeRecipient = feeRecipient_;
        emit FeeRecipientUpdated(feeRecipient_);
    }

    function setDefaultFeeBps(uint96 feeBps_) external onlyOwner {
        if (feeBps_ > MAX_FEE_BPS) revert InvalidFee();
        defaultFeeBps = feeBps_;
        emit DefaultFeeBpsUpdated(feeBps_);
    }

    // ============================================================
    // INTERNALS
    // ============================================================

    function _createIntent(
        address buyer,
        address seller,
        uint256 amount,
        uint256 workTimeoutSeconds,
        uint256 reviewPeriodSeconds,
        bytes32 workHash,
        string calldata workURI
    ) internal returns (uint256 intentId) {
        _validateIntentInputs(buyer, seller, amount, workTimeoutSeconds, reviewPeriodSeconds, workHash, workURI);

        intentId = nextIntentId++;
        uint256 workDeadline = block.timestamp + workTimeoutSeconds;

        intents[intentId] = Intent({
            buyer: buyer,
            seller: seller,
            feeBps: defaultFeeBps,
            amount: amount,
            createdAt: block.timestamp,
            workDeadline: workDeadline,
            reviewDeadline: 0,
            reviewPeriod: reviewPeriodSeconds,
            workHash: workHash,
            workURI: workURI,
            status: Status.Funded,
            proofURI: "",
            disputeURI: ""
        });

        usdc.safeTransferFrom(buyer, address(this), amount);

        emit IntentCreated(intentId, buyer, seller, amount, workHash, workURI, workDeadline, reviewPeriodSeconds, defaultFeeBps);
    }

    function _validateIntentInputs(
        address buyer,
        address seller,
        uint256 amount,
        uint256 workTimeoutSeconds,
        uint256 reviewPeriodSeconds,
        bytes32 workHash,
        string calldata workURI
    ) internal pure {
        if (seller == address(0) || buyer == address(0)) revert ZeroAddress();
        if (seller == buyer) revert SelfEscrow();
        if (amount == 0) revert InvalidAmount();
        if (workHash == bytes32(0)) revert InvalidWorkHash();
        _validateBasicURI(workURI);
        if (workTimeoutSeconds < MIN_WORK_TIMEOUT || workTimeoutSeconds > MAX_WORK_TIMEOUT) revert InvalidTimeout();
        if (reviewPeriodSeconds < MIN_REVIEW_PERIOD || reviewPeriodSeconds > MAX_REVIEW_PERIOD) {
            revert InvalidReviewPeriod();
        }
    }

    function _validateBasicURI(string calldata uri) internal pure {
        bytes memory b = bytes(uri);
        uint256 len = b.length;
        if (len == 0) revert InvalidURI();
        if (len > MAX_URI_BYTES) revert UriTooLong();
    }

    function _validateIPFSURI(string calldata uri) internal pure {
        bytes memory b = bytes(uri);
        uint256 len = b.length;
        if (len < 7) revert InvalidURI(); // Must be at least "ipfs://"
        if (len > MAX_URI_BYTES) revert UriTooLong();
        if (
            b[0] != 'i' || b[1] != 'p' || b[2] != 'f' || b[3] != 's' ||
            b[4] != ':' || b[5] != '/' || b[6] != '/'
        ) {
            revert InvalidURI();
        }
    }

    function _feeSplit(uint256 amount, uint96 feeBps) internal pure returns (uint256 feeAmount, uint256 sellerAmount) {
        feeAmount = (amount * feeBps) / BPS_DENOMINATOR;
        sellerAmount = amount - feeAmount;
    }
}
